-- --------------------------------------------------------
-- Native Starterkit Database Schema
-- Version: 2.0
-- Last Update: 2026-02-01
-- --------------------------------------------------------

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

-- --------------------------------------------------------
-- Core Tables
-- --------------------------------------------------------

--
-- Table: mst_user
-- Description: Master table for user accounts
--

CREATE TABLE IF NOT EXISTS `mst_user` (
  `id_user` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `nama` text NOT NULL,
  `nik` varchar(50) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` text NOT NULL,
  `level` varchar(50) DEFAULT NULL,
  `date_created` date NOT NULL,
  `image` varchar(255) NOT NULL DEFAULT 'default.png',
  `is_active` int(2) NOT NULL DEFAULT 1,
  `role_id` int(11) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Default SuperAdmin user
-- Password: superadmin (hashed)
--

INSERT INTO `mst_user` (`id_user`, `nama`, `nik`, `email`, `password`, `level`, `date_created`, `image`, `is_active`, `role_id`) VALUES
(1, 'superadmin', '696969', 'superadmin@app.com', '$2y$10$VUEKgUN6JfiE.Ka7.yKXI.Arwpcvy2IP1JV.csFCQFMGYPfCbkayO', 'SuperAdmin', CURDATE(), 'default.png', 1, 1)
ON DUPLICATE KEY UPDATE id_user = id_user;

-- --------------------------------------------------------

--
-- Table: user_role
-- Description: Defines user roles/groups
--

CREATE TABLE IF NOT EXISTS `user_role` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `role` varchar(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Default SuperAdmin role
--

INSERT INTO `user_role` (`id`, `role`) VALUES
(1, 'SuperAdmin')
ON DUPLICATE KEY UPDATE id = id;

-- --------------------------------------------------------

--
-- Table: user_menu
-- Description: Main menu items for sidebar navigation
--

CREATE TABLE IF NOT EXISTS `user_menu` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `menu` varchar(128) NOT NULL,
  `icon` varchar(100) NOT NULL DEFAULT 'fa fa-folder'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table: user_sub_menu
-- Description: Submenu items linked to main menus
--

CREATE TABLE IF NOT EXISTS `user_sub_menu` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `menu_id` int(11) NOT NULL,
  `title` varchar(128) NOT NULL,
  `is_active` int(1) NOT NULL DEFAULT 1,
  KEY `fk_submenu_menu` (`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table: user_access_menu
-- Description: Maps which roles can access which menus
--

CREATE TABLE IF NOT EXISTS `user_access_menu` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `role_id` int(11) NOT NULL,
  `menu_id` int(11) NOT NULL,
  UNIQUE KEY `role_menu_unique` (`role_id`, `menu_id`),
  KEY `fk_access_role` (`role_id`),
  KEY `fk_access_menu` (`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table: role_permissions
-- Description: Granular CRUD permissions for each role on each module
--

CREATE TABLE IF NOT EXISTS `role_permissions` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `role_id` int(11) NOT NULL,
  `module_name` varchar(128) NOT NULL,
  `can_view` tinyint(1) NOT NULL DEFAULT 0,
  `can_create` tinyint(1) NOT NULL DEFAULT 0,
  `can_update` tinyint(1) NOT NULL DEFAULT 0,
  `can_delete` tinyint(1) NOT NULL DEFAULT 0,
  UNIQUE KEY `role_module` (`role_id`, `module_name`),
  KEY `fk_role_permissions_role` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table: tbl_aplikasi
-- Description: Application settings and configuration
--

CREATE TABLE IF NOT EXISTS `tbl_aplikasi` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `nama_aplikasi` varchar(250) NOT NULL DEFAULT 'Native Starterkit',
  `alamat` varchar(250) NOT NULL DEFAULT '',
  `telp` varchar(50) NOT NULL DEFAULT '',
  `nama_developer` varchar(250) NOT NULL DEFAULT '',
  `logo` varchar(250) NOT NULL DEFAULT 'default_logo.png'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table: crud_history
-- Description: Tracks CRUD modules generated by the CRUD Generator
--

CREATE TABLE IF NOT EXISTS `crud_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `table_name` varchar(128) NOT NULL,
  `module_title` varchar(128) NOT NULL,
  `file_name` varchar(128) NOT NULL,
  `columns_config` text,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------
-- End of Core Schema
-- --------------------------------------------------------

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
